### ISSUE TITLE
 Exclude the issue owner's own comment from first response

### ISSUE THREAD

**Issue by eichisanden** [github/issue-metrics#101]
I think the comments of the owner of the issue themselves should be excluded from `Time to first response`.

Because they will add something that they forgot to write in the body of the Issue, or make additional comments to supplement the body of the Issue(like #26).

We could modify it as the default behavior, but if we are more cautious, we might add an option like `IGNORE_OWNER_COMMENT`.

**Comment by zkoppert** [comment]
I think that changing default behavior is okay in this case. Great catch on this situation. I normally modify my issue descriptions rather than comment to add more information so I wouldn't have thought of this one. I'm sure lots of people comment like described.
