### ISSUE TITLE
Feature: Create metrics using project status of an issue

### ISSUE THREAD

**Issue by SqaDomovik** [github/issue-metrics#120]
It would be a good idea to be able to generate a report that instead of using labels would use the status of the issue in a project, this would help to generate, for example, bug resolution progress reports with the times that the bug has been in each phase of its development. resolution.

|         | Open     | In progress | Resolved | To test | Tested |
|---------|----------|-------------|----------|---------|--------|
| Issue 1 | 00:22:32 |   5:23:00   |          |         |        |
| Issue 2 | 01:34:23 |   2:33:34   | 00:45:44 |         |        |
| Issue 3 |          |             |          |         |        |

**Comment by zkoppert** [comment]
That would be great! My understanding though is that we don't have access to this status data via the API. Check out https://github.com/github/issue-metrics/issues/57 for background on that.
