### ISSUE TITLE
Add author line for result in pull-requests

### ISSUE THREAD

**Issue by ostk0069** [github/issue-metrics#128]
I'm really happy to see author row for pull-request result.

Current: 
| Title | URL | Time to first response | Time to close | Time to answer |
| --- | --- | --- | --- | --- |
| Hoge | url | 0:01:55 | 0:56:43 | None |

Expected: 
| Title | URL | Author |Time to first response | Time to close | Time to answer |
| --- | --- | --- | --- | --- | --- |
| Hoge | url | @ostk0069 | 0:01:55 | 0:56:43 | None |

**Comment by Okabe-Junya** [comment]
Great!!

I think this is a wonderful idea. I have created a PR implementing this.

- #129 

However, attaching `@` may lead to sending out many mentions. It might be better not to include `@` (I have done so in the PR).
