### ISSUE TITLE
Only measure and issue for the columns that are reported

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#177]
Currently in the `get_per_issue_metrics()` function, it measure things like time to first response, time to answer, and time to close, even if those columns are marked as hidden via `HIDE_TIME_TO_FIRST_RESPONSE = true`

**Comment by uypham216** [comment]
Vay bay giờ tôi phải sửa làm sao nếu theo ý bạn.những gì bạn đóng góp cho dự án của tôi ngày hôm nay nói rieng và của all mọi người,Cộng đồng ngày một tốt hơn,phát triển bền vững và đi lên.xin chân thành cảm ơn  vì điều đó.

**Comment by zkoppert** [comment]
@uypham216 To fix this issue, we would need to update the `get_per_issue_metrics()` function to check if the `HIDE*` boolean is true before measuring the data.
