### ISSUE TITLE
`Error: Validation Failed` when creating an issue

### ISSUE THREAD

**Issue by toshimaru** [github/issue-metrics#183]
We run issue-metrics action every month.

However, I encountered an error:

```
Error: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

Any workaround for this?

**Comment by zkoppert** [comment]
Yes, there are 2 work around options:
- after running the issue-metrics step and before running the issue create step, you could truncate the file to only the first 65536 characters. You won't get the whole table and the table formatting may not render correctly. Not really ideal.
- upload the markdown file as an artifact to the workflow run. Then when you create an issue, mention in the issue text that the reader should go see the workflow run artifact that was uploaded. See https://github.com/actions/upload-artifact
