### ISSUE TITLE
Only CLOSED issues are calculated?

### ISSUE THREAD

**Issue by dtrezubSV** [github/issue-metrics#197]
After some testing trying to figure out why my reported times were all None, I figured only issues with status Closed have their : "Time in column" calculated.

Is there a way to include currently open issues in the calculations as well?

Also, if this is intentional, I don't see anything in the read.me :)

**Comment by dtrezubSV** [comment]
Exactly, sorry for the confusion.

**Comment by zkoppert** [comment]
Tested this and it looks like we have it working where if the issue is still open and has the label, the time in label will calculate the time between the label event and the current time. See https://github.com/github/issue-metrics/blob/e53d73ed4f09c640c595f4d27aab1961c583393a/labels.py#L84-L87

**Comment by dtrezubSV** [comment]
Thank you. Sorry for the confusion, I thought it was time spent in column. We can close this as a false alarm.
