### ISSUE TITLE
Related to github actions usage policy

### ISSUE THREAD

**Issue by Yaminyam** [github/issue-metrics#215]
https://github.com/github/issue-metrics#use-as-a-github-action
In the above article

"If you are running metrics on a repository other than the one where the workflow file is going to be, then update the value of GH_TOKEN. Do this by creating a GitHub API token with permissions to read the repo and write issues. Then take the value of the API token you just created, and create a repository secret where the name of the secret is GH_TOKEN and the value of the secret the API token. Then finally update the workflow file to use that repository secret by changing GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} to GH_TOKEN: ${{ secrets.GH_TOKEN }}. The name of the secret can really be anything. It just needs to match between when you create the secret name and when you refer to it in the workflow file."

The explanation for that part is
GitHub actions usage policy (https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions)
"if using GitHub-hosted runners, any other activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used."
I believe there is a possibility that it may be considered a violation of that part.
Isn't this a problem?

I don't think it's a problem with the repo, but with the above policy itself. In fact, I think GitHub Actions is being used a lot for automation that has nothing to do with CI.

**Comment by zkoppert** [comment]
After checking internally with folks that work on the GitHub Actions product, I don't believe this is a terms of service violation.
