### ISSUE TITLE
Prevent a big report to fail creating the issue

### ISSUE THREAD

**Issue by rolgalan** [github/issue-metrics#258]
### Is your feature request related to a problem?

Issue creation API has a limit of 65536 characters. Whenever the report is longer, the action fails with the following error:

`Error: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}`

This might happen easily when the amount of analyzed PRs is over ~300. 

### Describe the solution you'd like

I would like the action to validate the size of the report before submission, splitting the extra details into multiple comments if necessary (or just create the issue with whatever it fits) without failure.

### Describe alternatives you've considered

Alternatively, the action could support a config flag to include in the report only the first two tables with the basic stats, so all the details of each single PR are not reported.

### Additional context

Thanks!

**Comment by zkoppert** [comment]
Thanks for opening this issue! I've just been putting up with this and it hadn't crossed my mind that we could make this better. 😓 Great suggestion, I've opened up a pull request to address this.

**Comment by rolgalan** [comment]
That was so fast, thank you!
