### ISSUE TITLE
Specifying exception names in the overgeneral-exceptions

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#3]
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.

**Comment by ferrarimarco** [comment]
https://github.com/super-linter/super-linter/issues/5220 :)
