### ISSUE TITLE
Ability to hide `Number of items closed` Metric in the overview table

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#309]
### Is your feature request related to a problem?

`Number of items closed` as shown in the screenshot does not have any meaningful value when running the action against Discussions. Discussions are normally marked as answered rather than closed.

![Image](https://github.com/github/issue-metrics/assets/6935431/f703f710-96de-4584-9b5e-8f8ccb7cbdd0)

### Describe the solution you'd like

I would like to have the ability to configure `HIDE_ITEMS_CLOSED_COUNT` env variable such that it is not reported in the markdown output.

### Describe alternatives you've considered

Just dealing with it 🤷

**Comment by Piedone** [comment]
Even with `HIDE_TIME_TO_CLOSE: true` the "Number of items closed" line is there for me: https://github.com/github/issue-metrics/discussions/300

Also, for discussions, I'd welcome a "Number of items answered" metric instead (I suppose Time to answer already calculates with the same data).

**Comment by zkoppert** [comment]
Yeah I want a separate HIDE_* variable for the count because I feel like the count of closed items is a volume metric and the time to close is a velocity metric. Users may want one but not the other.

As for the number of items answered, I've created a [separate feature request for that](https://github.com/github/issue-metrics/issues/312).

Thanks for helping to shape how this action should work @Piedone! I really appreciate it! 🚀

**Comment by Piedone** [comment]
Oh great, thank you! And glad I could help!
