### ISSUE TITLE
Add "Numbers of times Review" the each Issue in Issue metrics.

### ISSUE THREAD

**Issue by Priyanka081** [github/issue-metrics#337]
### Is your feature request related to a problem?

If we see how many times one issue is reviewed by API will help to track the issue.

### Describe the solution you'd like

update the Issue metrics. I don't have a solution.

**Comment by zkoppert** [comment]
👋 @Priyanka081 Thanks for opening this issue! I'd love to understand more about what you are looking for here. Normally I think of pull requests as the ones having reviews and not issues. Are you thinking about pull requests or perhaps your looking for issue view counts? Let me know more about what you are looking for here.

**Comment by zkoppert** [comment]
Thanks for the screenshot and explanation! That helps a ton for me to understand what you're looking for.

Unfortunately due to GitHub API limitations we aren't able to determine what column an issue is in a project so we are unable to provide that in this action.
