### ISSUE TITLE
Support draft PRs

### ISSUE THREAD

**Issue by AlekSi** [github/issue-metrics#353]
### Describe the solution you'd like

> *For pull requests, these metrics exclude the time the PR was in draft mode.

It would be nice if this tool supported tracking time from the moment draft PR is created _in addition_ to other metrics (i.e. time from the moment PR is ready for review). In workflows, when draft PR is created ASAP when work on some issue is started, it would allow tracking cycle time of issues through associated PRs.

**Comment by zkoppert** [comment]
This is a great idea!

**Comment by zkoppert** [comment]
Taking a look at this. Working on implementing a "track_draft_prs" env variable. WIP

**Comment by zkoppert** [comment]
PR ready for review: https://github.com/github/issue-metrics/pull/415
