### ISSUE TITLE
Feature: Measure time to merge for pull requests

### ISSUE THREAD

**Issue by zkoppert** [github/issue-metrics#37]

**Comment by vibin** [comment]
Would this consider the time at which the first reviewer was assigned as the start time?

**Comment by zkoppert** [comment]
Great question! I had originally thought that it would be the time difference between when a pull request was opened to when it was merged. I think that may be the more comprehensive way to measure this since not all pull requests have a review before being merged.

**Comment by edmorley** [comment]
> time difference between when a pull request was opened to when it was merged

I think time spent in draft status would need to be excluded too?
