### ISSUE TITLE
Some configuration options don't work correctly

### ISSUE THREAD

**Issue by rakiyoshi** [github/issue-metrics#408]
### Describe the bug

The configurations `hide_label_metrics`, `hide_items_closed_count`, `non_mentioning_links`, `report_title`, and `output_file` don't work correctly in some conditions.

The `write_to_markdown` function has 15 arguments.
https://github.com/github/issue-metrics/blob/215054856ab0e929a22910979d738624b90c0b3a/markdown_writer.py#L82-L97

However, it is called with 14 arguments in `issue_metrics.py` because it lacks the argument `hide_label_metrics`.
https://github.com/github/issue-metrics/blob/215054856ab0e929a22910979d738624b90c0b3a/issue_metrics.py#L324-L338

This causes the argument `hide_label_metrics` and the following arguments not to work correctly.

### To Reproduce

To set a query that does not have subquery `type:discussions` in it and returns at least one issue.

### Expected behavior

The configurations `hide_label_metrics`, `hide_items_closed_count`, `non_mentioning_links`, `report_title`, and `output_file=output_file` work.

**Comment by zkoppert** [comment]
Well that's not good! I'll get a fix up for this. Thanks for the details!!
