### ISSUE TITLE
README workflow example misses the issues:write permission

### ISSUE THREAD

**Issue by julioz** [github/issue-metrics#60]
The workflow description in the README does not include the

```
permissions:
  issues: write
```

block, which causes workflow runs to [fail like this](https://github.com/github/issue-metrics/issues/53#issuecomment-1644155760).

**Comment by julioz** [comment]
Tangential but unrelated - would be nice if the action could provide a better error message. Right now, getting a python trace is not super helpful to find the lack of permission being the root cause.

**Comment by zkoppert** [comment]
Thanks, I've got some pull requests up to address both items.
