### ISSUE TITLE
Feature: Filter Out CI User Responses from Time to First Response 

### ISSUE THREAD

**Issue by philnielsen** [github/issue-metrics#65]
Hi! Awesome tool, I could definitely see us using it.

One thing that makes it sort of hard to use (at least for our org at the moment, which is why I thought the metrics were wrong in that other issue :) ) is that we have CI users that respond to PRs. This messes with the time to response calculations as they are always pretty quick to respond, and thus beat the human response most of the time. I've tested by removing the `first_comment_time` from this [line](https://github.com/github/issue-metrics/blob/580a22b2a3dbb585f412c9de45904b8cf53e92f9/time_to_first_response.py#L64) and re-running to get the actual time to first response (at least for us, assuming that a review comment is the first response is an ok assumption, I understand that isn't always true for everyone that would use this tool.)

My proposed solution would be to add a list of Users to ignore comments from, but I'm not really a Python person and can't tell how easy that would be to implement, since it looks like now you just pull the first comment from each issue, pr or discussion.

**Comment by zkoppert** [comment]
That proposed solution sounds feasible to me! I will put this on the todo list. Thanks for the suggestion!

**Comment by Okabe-Junya** [comment]
Thank you for the excellent CI workflow and thoughtful proposals!!

I have submitted a patch that resolves this issue, excluding certain users from the first response calculation. #78 

I hope this patch will be accepted and merged soon.
