### ISSUE TITLE
Is repo required?

### ISSUE THREAD

**Issue by stnguyen90** [github/issue-metrics#67]
The README states `SEARCH_QUERY` "must contain a `repo:` entry or an `org:` entry.", but when only supplying an org, an error occurs:

> ValueError: The search query for issues/prs must include a repository owner and name

Is this expected?

**Comment by zkoppert** [comment]
This is not expected behavior so I'll look into what is causing the problem.

**Comment by paul-uz** [comment]
Does this mean the search query can actually search an entire organisation?

**Comment by zkoppert** [comment]
@paul-uz Yes, the search query can search an entire organization but the results are limited to 1000 items due to the github API.
